services:
  db:
    build:
      context: ./TicTacToe.Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
      
  server:
    build:
      context: ./TicTacToe.Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./TicTacToe.Server:/src
